export const POLICY_CATEGORIES = [
  {
    name: "Corporate Governance",
    color: "bg-blue-500",
    policies: [
      "Company Governance Policy",
      "Code of Conduct",
      "Business Ethics Policy",
      "Corporate Social Responsibility Policy",
      "Anti-Bribery and Anti-Corruption Policy",
      "Gifts, Benefits and Hospitality Policy",
      "Conflict of Interest Policy",
      "Fraud Prevention Policy",
      "Whistleblower Policy",
      "Privacy Policy",
      "Confidentiality Policy",
      "Document Control Policy",
      "Record Management Policy",
      "Business Continuity Policy",
      "Disaster Recovery Policy",
      "Risk Management Policy",
      "Insurance Management Policy",
      "Delegation of Authority Policy",
      "Financial Management Policy",
      "Procurement Policy",
      "Asset Management Policy",
      "Sustainability Policy",
      "Environmental Responsibility Policy",
    ],
  },
  {
    name: "Human Resources",
    color: "bg-emerald-500",
    policies: [
      "Recruitment and Selection Policy",
      "Equal Employment Opportunity Policy",
      "Diversity and Inclusion Policy",
      "Indigenous Employment Policy",
      "Labour Hire Employment Policy",
      "Employment Classification Policy",
      "Employment Contracts Policy",
      "Casual Employment Policy",
      "Fixed Term Employment Policy",
      "Full Time Employment Policy",
      "Part Time Employment Policy",
      "Employee Induction Policy",
      "Probation Policy",
      "Performance Management Policy",
      "Employee Development Policy",
      "Promotion Policy",
      "Internal Transfer Policy",
      "Workplace Behaviour Policy",
      "Respect at Work Policy",
      "Bullying Prevention Policy",
      "Sexual Harassment Prevention Policy",
      "Workplace Harassment Policy",
      "Workplace Violence Policy",
      "Disciplinary Policy",
      "Grievance Resolution Policy",
      "Employee Assistance Program Policy",
      "Flexible Work Policy",
      "Leave Management Policy",
      "Payroll Policy",
      "Timesheet Policy",
      "Superannuation Policy",
      "Salary Sacrifice Policy",
      "Employee Benefits Policy",
      "Company Vehicle Policy",
      "Travel and Accommodation Policy",
      "Expense Reimbursement Policy",
      "Uniform and PPE Policy",
      "Drug and Alcohol Policy",
      "Fatigue Management Policy",
      "Fitness for Work Policy",
      "Return to Work Policy",
      "Workers Compensation Policy",
      "Employee Separation Policy",
      "Exit Interview Policy",
      "Redundancy Policy",
    ],
  },
  {
    name: "Labour Hire Operations",
    color: "bg-amber-500",
    policies: [
      "Labour Hire Compliance Policy",
      "Host Employer Management Policy",
      "Client Onboarding Policy",
      "Candidate Screening Policy",
      "Candidate Verification Policy",
      "Reference Checking Policy",
      "Competency Verification Policy",
      "VOC Management Policy",
      "Licence Verification Policy",
      "High Risk Work Licence Policy",
      "Medical Assessment Policy",
      "Pre-Employment Medical Policy",
      "Drug and Alcohol Testing Policy",
      "Site Mobilisation Policy",
      "Workforce Allocation Policy",
      "Placement Management Policy",
      "Client Site Induction Policy",
      "Employee Mobilisation Policy",
      "Demobilisation Policy",
      "Labour Hire Performance Review Policy",
      "Host Employer Consultation Policy",
      "Client Feedback Policy",
      "Candidate Database Management Policy",
      "Recruitment Marketing Policy",
      "Talent Pool Management Policy",
      "Workforce Planning Policy",
      "Skills Matrix Policy",
      "Availability Management Policy",
      "Stand Down Policy",
      "Redeployment Policy",
      "Workforce Retention Policy",
      "FIFO Workforce Management Policy",
      "Regional Workforce Management Policy",
    ],
  },
  {
    name: "Work Health and Safety",
    color: "bg-red-500",
    policies: [
      "Work Health and Safety Policy",
      "Safety Management System Policy",
      "Hazard Management Policy",
      "Risk Assessment Policy",
      "Safe Work Procedure Policy",
      "Job Hazard Analysis Policy",
      "Take 5 Policy",
      "Incident Reporting Policy",
      "Incident Investigation Policy",
      "Near Miss Reporting Policy",
      "Corrective Action Policy",
      "Preventative Action Policy",
      "Emergency Management Policy",
      "Emergency Response Policy",
      "First Aid Policy",
      "Injury Management Policy",
      "Manual Handling Policy",
      "Working Alone Policy",
      "Heat Stress Policy",
      "Mental Health and Wellbeing Policy",
      "Fatigue Risk Management Policy",
      "PPE Management Policy",
      "Electrical Safety Policy",
      "Isolation and Lock Out Tag Out Policy",
      "Working at Heights Policy",
      "Confined Space Policy",
      "Excavation Policy",
      "Mobile Plant Safety Policy",
      "Vehicle Safety Policy",
      "Journey Management Policy",
      "Remote Area Travel Policy",
      "Traffic Management Policy",
      "Hazardous Chemicals Policy",
      "Dangerous Goods Policy",
      "Environmental Incident Policy",
      "Waste Management Policy",
      "Fitness for Work Policy",
      "Alcohol and Other Drugs Policy",
      "Site Safety Inspection Policy",
      "Safety Observation Policy",
      "Contractor Safety Management Policy",
      "Visitor Safety Policy",
    ],
  },
  {
    name: "Quality Management",
    color: "bg-purple-500",
    policies: [
      "Quality Policy",
      "Continuous Improvement Policy",
      "Customer Satisfaction Policy",
      "Internal Audit Policy",
      "Corrective Action Policy",
      "Preventative Action Policy",
      "Non-Conformance Policy",
      "Management Review Policy",
      "Change Management Policy",
      "Process Improvement Policy",
    ],
  },
  {
    name: "Information Technology",
    color: "bg-cyan-500",
    policies: [
      "Information Security Policy",
      "Cyber Security Policy",
      "Password Management Policy",
      "Multi-Factor Authentication Policy",
      "Acceptable Use of Technology Policy",
      "Mobile Device Policy",
      "Email Usage Policy",
      "Internet Usage Policy",
      "Artificial Intelligence Usage Policy",
      "Data Backup Policy",
      "Data Retention Policy",
      "Cloud Storage Policy",
      "Software Management Policy",
      "Remote Access Policy",
      "Social Media Policy",
    ],
  },
  {
    name: "Finance",
    color: "bg-green-600",
    policies: [
      "Accounts Receivable Policy",
      "Accounts Payable Policy",
      "Credit Management Policy",
      "Debt Collection Policy",
      "Banking Policy",
      "Purchasing Policy",
      "Supplier Management Policy",
      "Expense Approval Policy",
      "Credit Card Policy",
      "Petty Cash Policy",
      "Budget Management Policy",
    ],
  },
  {
    name: "Legal and Compliance",
    color: "bg-indigo-500",
    policies: [
      "Modern Slavery Policy",
      "Industrial Relations Policy",
      "Fair Work Compliance Policy",
      "Labour Hire Licensing Compliance Policy",
      "Privacy Compliance Policy",
      "Records Retention Policy",
      "Intellectual Property Policy",
      "Legal Compliance Policy",
      "Contract Management Policy",
      "Subcontractor Management Policy",
    ],
  },
  {
    name: "Operations",
    color: "bg-orange-500",
    policies: [
      "Client Relationship Management Policy",
      "Service Delivery Policy",
      "Complaints Handling Policy",
      "Non-Conformance Reporting Policy",
      "Corrective Action Policy",
      "Business Development Policy",
      "Tender Management Policy",
      "Marketing Policy",
      "Brand Management Policy",
      "Communication Policy",
      "Meeting Management Policy",
    ],
  },
  {
    name: "Environment",
    color: "bg-teal-500",
    policies: [
      "Environmental Management Policy",
      "Pollution Prevention Policy",
      "Waste Disposal Policy",
      "Fuel Management Policy",
      "Spill Response Policy",
      "Noise Management Policy",
      "Dust Management Policy",
      "Environmental Compliance Policy",
    ],
  },
  {
    name: "Security",
    color: "bg-slate-500",
    policies: [
      "Site Security Policy",
      "Physical Security Policy",
      "Visitor Management Policy",
      "Identity Verification Policy",
      "Access Control Policy",
      "Key Management Policy",
    ],
  },
  {
    name: "Mining-Specific",
    color: "bg-yellow-600",
    policies: [
      "Mine Site Readiness Policy",
      "Client Site Compliance Policy",
      "Critical Risk Management Policy",
      "Verification of Competency Policy",
      "Safety Leadership Policy",
      "Shutdown Workforce Policy",
      "Project Mobilisation Policy",
      "Camp Behaviour Policy",
      "FIFO Conduct Policy",
      "Critical Controls Verification Policy",
    ],
  },
  {
    name: "Management Systems",
    color: "bg-rose-500",
    policies: [
      "Integrated Management System Policy",
      "Policy Review Policy",
      "Procedure Development Policy",
      "Forms and Records Policy",
      "KPI and Performance Monitoring Policy",
      "Continuous Improvement Register Policy",
    ],
  },
];

export const PRIORITY_POLICIES = [
  "Code of Conduct",
  "Recruitment and Selection Policy",
  "Labour Hire Compliance Policy",
  "Host Employer Management Policy",
  "Work Health and Safety Policy",
  "Drug and Alcohol Policy",
  "Fitness for Work Policy",
  "Fatigue Management Policy",
  "Incident Reporting Policy",
  "Hazard Management Policy",
  "Risk Assessment Policy",
  "PPE Policy",
  "Employee Induction Policy",
  "Candidate Verification Policy",
  "Competency Verification Policy",
  "Pre-Employment Medical Policy",
  "Licence Verification Policy",
  "Performance Management Policy",
  "Privacy Policy",
  "Information Security Policy",
  "Modern Slavery Policy",
  "Equal Employment Opportunity Policy",
  "Bullying and Harassment Policy",
  "Grievance Resolution Policy",
  "Document Control Policy",
  "Business Continuity Policy",
  "Environmental Management Policy",
  "Contractor Management Policy",
  "Client Onboarding Policy",
  "Workforce Allocation Policy",
];

export function policyKey(category, policy) {
  return `${category}::${policy}`;
}

export function getAllPolicies() {
  return POLICY_CATEGORIES.flatMap((cat) =>
    cat.policies.map((p) => ({ category: cat.name, policy: p, color: cat.color }))
  );
}

export function isPriority(policy) {
  return PRIORITY_POLICIES.includes(policy);
}